'use strict';
let csrf='',properties=[],editing=null;
const $=id=>document.getElementById(id),notice=$('notice');
function message(text,bad=false){notice.textContent=text;notice.className=bad?'error':'ok';}
async function api(route,options={}){const response=await fetch('/api/admin/'+route,{credentials:'same-origin',cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...options.headers}});const result=await response.json();if(!response.ok)throw Error(result.error||'Erro de conexão');return result;}
function show(logged){$('login').classList.toggle('hidden',logged);$('workspace').classList.toggle('hidden',!logged);}
async function loadAiConfig(){try{const status=await api('ai-config');$('ai-status').textContent=status.configured?'Groq conectada. O botão Gerar descrição usa IA.':'Groq ainda não conectada. Use a chave gratuita para ativar descrições com IA.';$('ai-config-form').classList.toggle('hidden',status.configured);}catch{$('ai-status').textContent='Não foi possível consultar a configuração da IA.';}}
async function load(){const data=await api('properties');properties=data.properties;const list=$('list');list.replaceChildren();if(!properties.length){list.textContent='Nenhum imóvel cadastrado ainda.';return;}for(const p of properties){const row=document.createElement('div');row.className='item';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=p.fields.titulo;const meta=document.createElement('small');meta.className='muted';meta.textContent=`${p.fields.bairro} · ${p.photos.length} foto(s) · ${p.status==='published'?'Publicado':p.status}`;info.append(title,meta);const actions=document.createElement('div');actions.className='actions';const edit=document.createElement('button');edit.className='secondary';edit.textContent='Editar';edit.onclick=()=>editProperty(p);const toggle=document.createElement('button');toggle.className='secondary';toggle.textContent=p.status==='published'?'Pausar':'Publicar';toggle.onclick=async()=>{try{await api('status',{method:'POST',body:JSON.stringify({id:p.id,status:p.status==='published'?'pausar':'published'})});await load();}catch(e){message(e.message,true);}};actions.append(edit,toggle);row.append(info,actions);list.append(row);}}
function editProperty(p){editing=p.id;for(const [k,v] of Object.entries(p.fields))if($('property-form').elements[k])$('property-form').elements[k].value=v;$('form-heading').textContent='Editar imóvel';$('save').textContent='Salvar alterações';$('cancel').classList.remove('hidden');$('preview').textContent=`${p.photos.length} foto(s) já cadastrada(s). Novas fotos serão adicionadas.`;scrollTo({top:0,behavior:'smooth'});}
function reset(){editing=null;$('property-form').reset();$('form-heading').textContent='Novo imóvel';$('save').textContent='Publicar imóvel';$('cancel').classList.add('hidden');$('preview').replaceChildren();$('description-source').textContent='';}
async function resize(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Cada foto deve ser JPG, PNG ou WebP com até 10 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.78);}finally{bitmap.close();}}
$('photos').onchange=()=>{const box=$('preview');box.replaceChildren();for(const file of $('photos').files){const img=document.createElement('img');img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src);img.alt=file.name;box.append(img);}};
$('ai-config-form').onsubmit=async e=>{e.preventDefault();const button=$('ai-save');button.disabled=true;$('ai-status').textContent='Verificando chave na Groq...';try{await api('ai-config',{method:'POST',body:JSON.stringify({key:$('ai-key').value})});$('ai-key').value='';await loadAiConfig();message('IA conectada. Agora gere uma descrição para conferir.');}catch(error){$('ai-status').textContent='Groq não conectada.';message(error.message,true);}finally{button.disabled=false;}};
$('login-form').onsubmit=async e=>{e.preventDefault();try{const result=await api('login',{method:'POST',body:JSON.stringify({username:$('user').value,password:$('password').value})});csrf=result.csrf;$('password').value='';show(true);await load();await loadAiConfig();message('Acesso autorizado.');}catch(error){message(error.message,true);}};
$('property-form').onsubmit=async e=>{e.preventDefault();const save=$('save');save.disabled=true;message('Preparando fotos...');try{const photos=[];if($('photos').files.length>20)throw Error('Selecione até 20 fotos.');for(const file of $('photos').files)photos.push(await resize(file));if(JSON.stringify(photos).length>15*1024*1024)throw Error('Fotos muito grandes; selecione menos fotos.');const fields=Object.fromEntries(new FormData(e.target).entries());await api('properties',{method:'POST',body:JSON.stringify({id:editing,fields,photos})});reset();await load();message('Imóvel salvo e catálogo atualizado.');}catch(error){message(error.message,true);}finally{save.disabled=false;}};
$('generate-description').onclick=async()=>{if($('descricao').value.trim()&&!confirm('Substituir a descrição atual pelo texto gerado?'))return;const button=$('generate-description');button.disabled=true;$('description-source').textContent='Gerando descrição...';try{const fields=Object.fromEntries(new FormData($('property-form')).entries());const result=await api('description',{method:'POST',body:JSON.stringify({fields})});$('descricao').value=result.description;$('description-source').textContent=result.source==='ai'?'Texto gerado com IA (Groq). Revise antes de publicar.':'IA indisponível ou sem chave; texto automático usado. Revise antes de publicar.';message('Descrição pronta para revisão.');}catch(error){$('description-source').textContent='';message(error.message,true);}finally{button.disabled=false;}};
$('cancel').onclick=reset;
$('logout').onclick=async()=>{try{await api('logout',{method:'POST',body:'{}'});}finally{csrf='';$('ai-key').value='';show(false);message('Você saiu da conta.');}};
api('session').then(async data=>{csrf=data.csrf;show(true);await load();await loadAiConfig();}).catch(()=>show(false));
