'use strict';
const root=document.querySelector('#detail-content');
const id=new URLSearchParams(location.search).get('id');
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function render(p){
  document.title=`${p.titulo} | Seu Moura Imóveis`;
  root.replaceChildren();root.removeAttribute('role');
  const header=element('div','detail-heading');header.append(element('p','listing-type',p.finalidade==='aluguel'?'PARA ALUGAR':'À VENDA'),element('h1','',p.titulo),element('p','listing-location',[p.bairro,p.cidade].filter(Boolean).join(' · ')));
  const layout=element('div','detail-layout'),left=element('div','detail-main'),right=element('aside','detail-aside');
  const gallery=element('section','detail-gallery');const stage=element('div','detail-gallery-stage'),mainLink=document.createElement('a'),mainImage=document.createElement('img'),counter=element('span','detail-gallery-counter'),thumbs=element('div','detail-thumbnails');let currentPhoto=0;mainLink.target='_blank';mainLink.rel='noopener noreferrer';mainLink.setAttribute('aria-label','Abrir foto em tamanho original');mainImage.loading='eager';mainLink.append(mainImage);stage.append(mainLink);const thumbButtons=[];const showPhoto=index=>{currentPhoto=(index+p.photos.length)%p.photos.length;mainImage.src=p.photos[currentPhoto];mainImage.alt=`${p.titulo}, foto ${currentPhoto+1}`;mainLink.href=p.photos[currentPhoto];counter.textContent=`${currentPhoto+1} de ${p.photos.length}`;thumbButtons.forEach((button,i)=>button.classList.toggle('active',i===currentPhoto));};if(p.photos.length>1){const previous=element('button','detail-gallery-arrow detail-gallery-prev','‹'),next=element('button','detail-gallery-arrow detail-gallery-next','›');previous.type=next.type='button';previous.setAttribute('aria-label','Foto anterior');next.setAttribute('aria-label','Próxima foto');previous.onclick=()=>showPhoto(currentPhoto-1);next.onclick=()=>showPhoto(currentPhoto+1);stage.append(previous,next,counter);}for(const [i,src] of p.photos.entries()){const button=document.createElement('button'),thumb=document.createElement('img');button.type='button';button.className='detail-thumbnail';button.setAttribute('aria-label',`Mostrar foto ${i+1}`);thumb.src=src;thumb.alt='';thumb.loading=i?'lazy':'eager';button.append(thumb);button.onclick=()=>showPhoto(i);thumbButtons.push(button);thumbs.append(button);}gallery.append(stage,thumbs);left.append(gallery);showPhoto(0);
  const specs=element('dl','detail-specs');for(const [label,value,suffix] of [['Área',p.area,' m²'],['Quartos',p.quartos,''],['Banheiros',p.banheiros,'']]){if(value===undefined||value===null||value==='')continue;const item=document.createElement('div');item.append(element('dt','',label),element('dd','',String(value)+suffix));specs.append(item);}right.append(specs);
  const price=element('div','catalog-price');price.append(element('span','',p.finalidade==='aluguel'?'Aluguel mensal':'Valor de venda'),element('strong','',money.format(p.preco)));right.append(price);
  const contact=element('a','button cream detail-floating-cta','Tenho interesse ↗');contact.href='https://wa.me/5594992972083?text='+encodeURIComponent(`Olá, Seu Moura! Tenho interesse em ${p.titulo}. Ver imóvel: ${location.href}`);contact.target='_blank';contact.rel='noopener noreferrer';contact.setAttribute('aria-label','Falar no WhatsApp sobre '+p.titulo);layout.append(left,right);
  root.append(header,layout,contact);
  if(p.descricao?.trim()){const section=element('section','detail-description');section.append(element('h2','','Sobre este imóvel'),element('p','',p.descricao));root.append(section);}
  root.append(element('p','catalog-note','Valores e disponibilidade sujeitos à confirmação com a equipe da Seu Moura.'));
}
if(!id||!/^[a-f0-9-]{8,36}$/.test(id)){root.textContent='Imóvel não encontrado.';}else fetch('./api/properties',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Falha ao consultar imóveis');return r.json();}).then(data=>{const p=data.properties?.find(item=>item.id===id);if(!p){root.textContent='Este imóvel não está disponível.';return;}render(p);}).catch(()=>{root.textContent='Não foi possível carregar o imóvel. Tente novamente.';});
